### ISSUE TITLE
Document COVID attendance policy

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/secure-the-web-forward-workshop#13]

**Comment by torgo** [comment]
Data: https://www.w3.org/Privacy/permissions-ws-2022/code-of-conduct

**Comment by torgo** [comment]
Data: https://events.linuxfoundation.org/open-source-summit-north-america/attend/health-and-safety/

**Comment by torgo** [comment]
More data: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/attend/health-and-safety/

**Comment by tidoust** [comment]
Workshop will be a virtual event in the end. Closing.
